"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { FileJson, AlertCircle } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { parsePropertyJson, ParsedPropertyJson } from "@/lib/jsonParser";

export function ImportJsonModal({ onImport }: { onImport: (data: ParsedPropertyJson) => void }) {
  const [open, setOpen] = useState(false);
  const [jsonInput, setJsonInput] = useState("");
  const [parsedData, setParsedData] = useState<ParsedPropertyJson | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [missingFields, setMissingFields] = useState<string[]>([]);

  const handleParse = () => {
    setError(null);
    setMissingFields([]);
    setParsedData(null);

    if (!jsonInput.trim()) {
      setError("Please paste some JSON first.");
      return;
    }

    const result = parsePropertyJson(jsonInput);
    if (result.success && result.data) {
      setParsedData(result.data);
    } else {
      setError(result.error || "Failed to parse JSON");
      if (result.missingFields) setMissingFields(result.missingFields);
    }
  };

  const handleClear = () => {
    setJsonInput("");
    setError(null);
    setMissingFields([]);
    setParsedData(null);
  };

  const handleContinue = () => {
    if (parsedData) {
      onImport(parsedData);
      setOpen(false);
      handleClear();
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="border-primary/50 text-primary hover:bg-primary/10">
          <FileJson className="size-4 mr-2" /> Import JSON
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Import Property JSON</DialogTitle>
          <DialogDescription>
            Paste the structured JSON generated by an AI assistant to auto-fill the property details.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <Textarea 
            value={jsonInput}
            onChange={(e) => setJsonInput(e.target.value)}
            placeholder='{\n  "title": "...",\n  "price": "..."\n}'
            className="font-mono text-xs min-h-[250px] bg-background/50 border-primary/20"
          />

          <div className="flex justify-between items-center">
            <Button type="button" variant="ghost" onClick={handleClear}>Clear</Button>
            <Button type="button" onClick={handleParse} className="bg-primary text-primary-foreground">
              Parse JSON
            </Button>
          </div>

          {/* Validation Errors Section */}
          {(error || missingFields.length > 0) && (
            <div className="p-4 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive text-sm space-y-2">
              <div className="flex items-center gap-2 font-semibold">
                <AlertCircle className="size-4" />
                <span>{error}</span>
              </div>
              {missingFields.length > 0 && (
                <p>Missing required fields: {missingFields.join(", ")}</p>
              )}
            </div>
          )}

          {/* Preview Section */}
          {parsedData && (
            <div className="mt-6 space-y-4 border-t border-primary/20 pt-4">
              <h3 className="font-semibold text-lg">Preview</h3>
              
              <div className="grid grid-cols-2 gap-4 text-sm bg-background/50 p-4 rounded-xl border border-primary/10">
                <div>
                  <span className="text-muted-foreground text-xs block uppercase">Title</span>
                  <span className="font-medium">{parsedData.title}</span>
                </div>
                <div>
                  <span className="text-muted-foreground text-xs block uppercase">Price</span>
                  <span className="font-medium">{parsedData.price}</span>
                </div>
                <div>
                  <span className="text-muted-foreground text-xs block uppercase">Location</span>
                  <span className="font-medium">{parsedData.location}</span>
                </div>
                <div>
                  <span className="text-muted-foreground text-xs block uppercase">Type & BHK</span>
                  <span className="font-medium">{parsedData.propertyType} • {parsedData.bhk}</span>
                </div>
                <div className="col-span-2">
                  <span className="text-muted-foreground text-xs block uppercase">Description Snippet</span>
                  <span className="font-medium line-clamp-2">{parsedData.description}</span>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-sm bg-background/50 p-4 rounded-xl border border-primary/10">
                <div>
                  <span className="text-muted-foreground text-xs block uppercase mb-1">Amenities ({parsedData.amenities.length})</span>
                  <ul className="list-disc list-inside text-xs text-muted-foreground">
                    {parsedData.amenities.slice(0, 3).map(a => <li key={a}>{a}</li>)}
                    {parsedData.amenities.length > 3 && <li>...</li>}
                  </ul>
                </div>
                <div>
                  <span className="text-muted-foreground text-xs block uppercase mb-1">Landmarks ({parsedData.landmarks.length})</span>
                  <ul className="list-disc list-inside text-xs text-muted-foreground">
                    {parsedData.landmarks.slice(0, 3).map(a => <li key={a}>{a}</li>)}
                    {parsedData.landmarks.length > 3 && <li>...</li>}
                  </ul>
                </div>
                <div>
                  <span className="text-muted-foreground text-xs block uppercase mb-1">Contact Info</span>
                  <div className="text-xs text-muted-foreground">
                    <p>Phone: {parsedData.contact.phone || "None"}</p>
                    <p>WhatsApp: {parsedData.contact.whatsapp || "None"}</p>
                  </div>
                </div>
              </div>
              
              {parsedData.images.length > 0 && (
                <div className="bg-background/50 p-4 rounded-xl border border-primary/10 text-sm">
                  <span className="text-muted-foreground text-xs block uppercase mb-2">Gallery ({parsedData.images.length})</span>
                  <div className="flex gap-2 overflow-x-auto pb-2">
                    {parsedData.images.map((img, i) => (
                      <div key={i} className="shrink-0 size-16 rounded overflow-hidden border border-primary/20 bg-muted flex items-center justify-center">
                        {img.startsWith("http") ? (
                          <img src={img} alt="" className="w-full h-full object-cover" />
                        ) : (
                          <span className="text-[10px] text-center px-1">Invalid URL</span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <Button onClick={handleContinue} className="w-full bg-primary text-primary-foreground mt-4">
                Continue to Edit
              </Button>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
